[package]
name = "marshmelly/cafe"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.4.7"
Component = "sleitnick/component@2.4.6"
EnumList = "sleitnick/enum-list@2.0.1"
Streamable = "sleitnick/streamable@1.2.4"
Trove = "sleitnick/trove@0.5.0"	
Signal = "sleitnick/signal@1.2.1"
Timer = "sleitnick/timer@1.1.2"
Promise = "evaera/promise@4.0.0"
Janitor = "howmanysmall/janitor@>1"
Cmdr = "evaera/cmdr@1.9.0"
Roact = "roblox/roact@>=1"