local module = {
	["Atmosphere"] = {
		["Density"] = 0.362,
		["Offset"] = 0,
		["Color"] = Color3.fromRGB(124, 123, 123),
		["Decay"] = Color3.fromRGB(45, 92, 90),
		["Glare"] = 0,
		["Haze"] = 1.12
	},
	
	["Sky"] = {
		["SkyboxBk"] = "rbxassetid://600830446",
		["SkyboxDn"] = "rbxassetid://600831635",
		["SkyboxFt"] = "rbxassetid://600832720",
		["SkyboxLf"] = "rbxassetid://600886090",
		["SkyboxRt"] = "rbxassetid://600833862",
		["SkyboxUp"] = "rbxassetid://600835177",
	},
	
	["ColorCorrectionEffect"] = {
		["Brightness"] = 0.1,
		["Contrast"] = 0,
		["Saturation"] = 0.1,
		["TintColor"] = Color3.fromRGB(225, 215, 198)
	}
}

return module
