local Items = {
	
	Bullet = {
		Name = "Bullets",
		Value = 10,
		Type = "Ammo"
	},
	
	PlasmaCell = {
		Name = "Plasma Cell",
		Value = 40,
		Type = "Ammo"
	},
	
	FusionCell = {
		Name = "Fusion Cell",
		Value = 20,
		Type = "Ammo"
	},
	
	LaserRifle = {
		Name = "Laser Rifle",
		Value = 600,
		Type = "Primary"
	},
	
	PlasmaRifle = {
		Name = "Plasma Rifle",
		Value = 800,
		Type = "Primary"
	},
	
	LaserPistol = {
		Name = "Laser Pistol",
		Value = 300,
		Type = "Secondary"
	},
	
	AutomaticRifle = {
		Name = "Automatic Rifle",
		Value = 200,
		Type = "Primary"
	},

	["GamepassAutomaticRifle"] = {
		Name = "Automatic Rifle (Gamepass)",
		Value = 200,
		Type = "Primary"
	},
	
	["10mmPistol"] = {
		Name = "10mm Pistol",
		Value = 100,
		Type = "Secondary"
	},

	["Gamepass10mmPistol"] = {
		Name = "10mm Pistol (Gamepass)",
		Type = "Secondary",
		GamepassId = 755960403
	},

	Minigun = {
		Name = "Minigun",
		Value = 10000,
		Type = "Primary"
	}	
}

return Items