local Items = {
	
	Bullet = {
		Name = "Bullet",
		Value = 5,
		Type = "Ammo"
	},
	
	PlasmaCell = {
		Name = "Plasma Cell",
		Value = 20,
		Type = "Ammo"
	},
	
	FusionCell = {
		Name = "Fusion Cell",
		Value = 10,
		Type = "Ammo"
	},
	
	LaserRifle = {
		Name = "Laser Rifle",
		Value = 600,
		Type = "Primary"
	},
	
	PlasmaRifle = {
		Name = "Plasma Rifle",
		Value = 1000,
		Type = "Primary"
	},
	
	LaserPistol = {
		Name = "Laser Pistol",
		Value = 400,
		Type = "Secondary"
	},
	
	AutomaticRifle = {
		Name = "Automatic Rifle",
		Value = 300,
		Type = "Primary"
	},
	
	["10mmPistol"] = {
		Name = "10mm Pistol",
		Value = 150,
		Type = "Secondary"
	},

	Minigun = {
		Name = "Minigun",
		Value = 10000,
		Type = "Primary"
	}	
}

return Items